version: '3.6'
services:
  api-gw:
    build: 
      context: ./
      dockerfile: ./api-gw/Dockerfile
      # uprav ked bude treba production na production
      target: development
    volumes:
      - ./api-gw/:/src/
      - ./utils:/utils/
    ports: 
      - 8001:8000
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  
  service1:
    build: 
      context: ../
      dockerfile: ./service1/Dockerfile
    ports: 
      - 8000:8000

  # udf:
    # Uncomment the next line to use a non-root user for all processes. You can also
    # simply use the "remoteUser" property in devcontainer.json if you just want VS Code
    # and its sub-processes (terminals, tasks, debugging) to execute as the user. On Linux,
    # you may need to update USER_UID and USER_GID in .devcontainer/Dockerfile to match your
    # user if not 1000. See https://aka.ms/vscode-remote/containers/non-root for details.
    # user: node

    # build: 
      # context: .
      # dockerfile: Dockerfile
    
    # volumes:
    #   - ..:/workspace:cached
      
    # # Overrides default command so things don't shut down after the process ends.
    # command: sleep infinity

    # # links:
    # #   - db

  # db:
  #   image: postgres
  #   restart: unless-stopped
  #   ports: 
  #     - 5432:5432
  #   environment:
  #     POSTGRES_PASSWORD: mysecretpassword
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: conference
 
