version: '3.6'
services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  authservice:
    build: 
      context: ./
      dockerfile: ./authservice/Dockerfile
      # uprav ked bude treba production na production
      target: development
    volumes:
      - ./authservice/:/src/
      - ./utils:/utils/

  service1:
    build: 
      context: ./
      dockerfile: ./service1/Dockerfile
      # uprav ked bude treba production na production
      target: development
    volumes:
      - ./service1/:/src/
      - ./utils:/utils/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.service1.rule=Host(`service1.localhost`)"
      - "traefik.http.routers.service1.entrypoints=web"
      # Forward authentication to example.com
      - "traefik.http.middlewares.service1-auth.forwardauth.address=http://authservice:8000"      
      - "traefik.http.routers.service1.middlewares=service1-auth@docker"

  service2:
    build: 
      context: ./
      dockerfile: ./service2/Dockerfile
      # uprav ked bude treba production na production
      target: development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.service2.rule=Host(`service2.localhost`)"
      - "traefik.http.routers.service2.entrypoints=web"
    volumes:
      - ./service2/:/src/
      - ./utils:/utils/
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    # healthcheck:
    #   test: ["CMD", "wget", "--quiet --tries=1 --spider", "http://service2.localhost"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
     
  backservice:
    build: 
      context: ./
      dockerfile: ./backservice/Dockerfile
      # uprav ked bude treba production na production
      target: development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backservice.rule=Host(`backservice.localhost`)"
      - "traefik.http.routers.backservice.entrypoints=web"
    volumes:
      - ./backservice/:/src/
      - ./utils:/utils/
    ports: 
      - 8000:8000
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"