version: '3.6'
services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  
  # Authentication service. Will authenticate requests going to fe_service_auth
  auth_service:
    build: 
      context: ./
      dockerfile: ./auth_service/Dockerfile
      # uprav ked bude treba production na production
      target: development
    volumes:
      - ./auth_service/:/src/
      - ./utils:/utils/

  # Front end service. Before coming to the service the request is authenticated by
  # authentication service. If authenticated, the request proceeds to the service , which passes 
  # the request further to backen service
  # Domain : fe_service_auth.localhost
  fe_service_auth:
    build: 
      context: ./
      dockerfile: ./fe_service_auth/Dockerfile
      # uprav ked bude treba production na production
      target: development
    volumes:
      - ./fe_service_auth/:/src/
      - ./utils:/utils/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fe_service_auth.rule=Host(`fe_service_auth.localhost`)"
      - "traefik.http.routers.fe_service_auth.entrypoints=web"
      # Forward authentication to auth_service. 
      # Create fe_service_auth-auth middleware, whic forwards the request to adress
      - "traefik.http.middlewares.fe_service_auth-auth.forwardauth.address=http://auth_service:8000"      
      # Tell the fe_service_auth router to route the requests to the middleware above
      - "traefik.http.routers.fe_service_auth.middlewares=fe_service_auth-auth@docker"

  # Front end service. Not authenticated
  # Domain : fe_service_notauth.localhost
  fe_service_notauth:
    build: 
      context: ./
      dockerfile: ./fe_service_notauth/Dockerfile
      # uprav ked bude treba production na production
      target: development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fe_service_notauth.rule=Host(`fe_service_notauth.localhost`)"
      - "traefik.http.routers.fe_service_notauth.entrypoints=web"
    volumes:
      - ./fe_service_notauth/:/src/
      - ./utils:/utils/
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    # healthcheck:
    #   test: ["CMD", "wget", "--quiet --tries=1 --spider", "http://fe_service_notauth.localhost"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
     
  # Back end service. Without interface from outside world
  be_service:
    build: 
      context: ./
      dockerfile: ./be_service/Dockerfile
      # uprav ked bude treba production na production
      target: development
    volumes:
      - ./be_service/:/src/
      - ./utils:/utils/
    # ports: 
    #   - 8000:8000
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"